version: "3.8"

networks:
  test_network:
    driver: bridge

services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    ports: 
      - "15672:15672" 
      - "5672:5672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 30s
      timeout: 30s
      retries: 3
    networks:
      - test_network
  
  producer:
    build: Producer/
    ports:
      - "5000:5000"
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - test_network

  consumer_insert_item:
    build: Consumer_2/
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - test_network
  
  consumer_order_processing:
    build: ./Consumer_4
    depends_on:
      - rabbitmq

